// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQCz4wVfGVaPjfKKYbqLOG4karnpaeWnk',
    appId: '1:1095992659257:web:392af6e1176964b3d52ce8',
    messagingSenderId: '1095992659257',
    projectId: 'stable-reactor-386614',
    authDomain: 'stable-reactor-386614.firebaseapp.com',
    storageBucket: 'stable-reactor-386614.appspot.com',
    measurementId: 'G-5H5NX297XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6jxSmI69W9FZcXGtN_AO5Gmbc56A7-8',
    appId: '1:1095992659257:android:fd6ba21ce9cbaaedd52ce8',
    messagingSenderId: '1095992659257',
    projectId: 'stable-reactor-386614',
    storageBucket: 'stable-reactor-386614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZX3MryJIgbOwoLsYultF5_TpW99v3Hg0',
    appId: '1:1095992659257:ios:437bd5644cf9cb4ed52ce8',
    messagingSenderId: '1095992659257',
    projectId: 'stable-reactor-386614',
    storageBucket: 'stable-reactor-386614.appspot.com',
    iosBundleId: 'com.example.mylastapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZX3MryJIgbOwoLsYultF5_TpW99v3Hg0',
    appId: '1:1095992659257:ios:0fe36e1b18ea08a1d52ce8',
    messagingSenderId: '1095992659257',
    projectId: 'stable-reactor-386614',
    storageBucket: 'stable-reactor-386614.appspot.com',
    iosBundleId: 'com.example.mylastapp.RunnerTests',
  );
}
